# Generated by Django 2.2.9 on 2020-01-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20200109_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(null=True, upload_to='gallery', verbose_name='Image'),
        ),
    ]
